dist: bionic

services:
  - docker

language: go

go:
  - "1.13"
  - "1.14"

_iRODS_4_2_8: &iRODS_4_2_8 DOCKER_IMAGE="wsinpg/ub-18.04-irods-4.2.8:latest" IRODS_VERSION="==4.2.8" BATON_VERSION=">2.0.1"

env:
  global:
    - GO111MODULE=on
    - WSI_CONDA_CHANNEL="https://dnap.cog.sanger.ac.uk/npg/conda/devel/generic"
  jobs:
    - DOCKER_IMAGE="wsinpg/ub-16.04-irods-4.2.7:latest" IRODS_VERSION="==4.2.7" BATON_VERSION=">2.0.1"
    - *iRODS_4_2_8

jobs:
  allow_failures:
    - go: "1.13"
      env: *iRODS_4_2_8
    - go: "1.14"
      env: *iRODS_4_2_8

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

before_install:
  - docker pull "$DOCKER_IMAGE"
  - docker run -d -p 1247:1247 "$DOCKER_IMAGE"
  - docker ps -a

install:
  - ./scripts/travis_install.sh

script:
  - ./scripts/travis_script.sh

